project_id = "euyidvolwqmzijkfrplh"

[functions.telegram-webhook]
verify_jwt = false

[functions.connect-telegram-bot]
verify_jwt = false

[functions.connect-bot]
verify_jwt = false

[functions.generate-voice]
verify_jwt = false

[functions.generate-video]
verify_jwt = false